CREATE TABLE players(
  id INTEGER PRIMARY KEY, name TEXT, placement VARCHAR);
INSERT INTO players VALUES (1, "Mystical Man", 1);
INSERT INTO players VALUES (2, "Cheesy", 3);
INSERT INTO players VALUES (3, "Eliks", 2);
INSERT INTO players VALUES (4, "Kriz", "NA");
INSERT INTO players VALUES (5, "LLucky Gaming", 4);
CREATE TABLE levels(
  placement INTEGER PRIMARY KEY, name TEXT, difficulty TEXT, player VARCHAR);
INSERT INTO levels VALUES (1, "Aquatic Extremeness", "Extreme Demon", "Mystical Man");
INSERT INTO levels VALUES (2, "8 Jumps of Hell", "Extreme Challenge", "eliks");
INSERT INTO levels VALUES (3, "Solar Circles", "Medium Demon", "Mystical Man");
INSERT INTO levels VALUES (4, "Problematic", "Easy Demon", "Mystical Man");
INSERT INTO levels VALUES (5, "Trump Circles", "Easy Demon", "Mystical Man");
INSERT INTO levels VALUES (6, "Space Circles", "Easy Demon", "Mystical Man");
INSERT INTO levels VALUES (7, "Ratio Circles", "Easy Demon", "Mystical Man");
INSERT INTO levels VALUES (8, "DeCode", "Easy Demon", "Mystical Man");
INSERT INTO levels VALUES (9, "Ultra Paracosm", "Easy Demon", "Mystical Man");
INSERT INTO levels VALUES (10, "Infinite Circles", "Easy Demon", "Mystical Man");
INSERT INTO levels VALUES (11, "Ispywithmylittleeye", "Easy Demon", "Cheesy");
INSERT INTO levels VALUES (12, "Invisible Clubstep", "Easy Demon", "Mystical Man");
INSERT INTO levels VALUES (13, "The Nightmare", "Easy Demon", "Mystical Man");
INSERT INTO levels VALUES (14, "The Lightning Road", "Easy Demon", "Mystical Man");
INSERT INTO levels VALUES (15, "8o", "Insane Demon", "eliks");
INSERT INTO levels VALUES (16, "Dingusatiroenit", "Extreme Demon", "eliks");
CREATE TABLE contact(id INTEGER PRIMARY KEY, name TEXT, email TEXT);
INSERT INTO contact VALUES (1, "Mystical Man", "Alkanuit@gmail.com");
CREATE TABLE impossiblelevels(Dashercrateid INTEGER PRIMARY KEY, name TEXT, creator VARCHAR);
INSERT INTO impossiblelevels VALUES (1, "Cyclolcyc", "Eightos");
INSERT INTO impossiblelevels VALUES (2, "Formosa", "Eightos");
INSERT INTO impossiblelevels VALUES (3, "Ballistic Wistfully", "Eightos");
INSERT INTO impossiblelevels VALUES (4, "RAIN", "Skyyee");
INSERT INTO impossiblelevels VALUES (5, "wistfully", "Xialoumi");
INSERT INTO impossiblelevels VALUES (6, "CUM" "AuraXalaiv");
INSERT INTO impossiblelevels VALUES (7, "METH DEATH X", "AuraXalaiv");
INSERT INTO impossiblelevels VALUES (8, "arcturus unnerfed" "maxfs");
INSERT INTO impossiblelevels VALUES (9, "Shipping", "Apocalipse");
INSERT INTO impossiblelevels VALUES (10, "Joke Resubmission", "Relayne");
